# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'serverManager.ui'
#
# Created: Fri Jan 28 15:57:23 2011
#      by: pyside-uic 0.2.6 running on PySide 1.0.0~beta3
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(452, 412)
        #pylint: disable=W0201
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(0, 5, 0, 5)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Contrl_tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.Contrl_tabWidget.setObjectName("Contrl_tabWidget")
        self.serverControl_tab = QtGui.QWidget()
        self.serverControl_tab.setObjectName("serverControl_tab")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.serverControl_tab)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.serverControl_groupBox = QtGui.QGroupBox(self.serverControl_tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.serverControl_groupBox.sizePolicy().hasHeightForWidth())
        self.serverControl_groupBox.setSizePolicy(sizePolicy)
        self.serverControl_groupBox.setObjectName("serverControl_groupBox")
        self.gridLayout = QtGui.QGridLayout(self.serverControl_groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.startServer_pushButton = QtGui.QPushButton(self.serverControl_groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.startServer_pushButton.sizePolicy().hasHeightForWidth())
        self.startServer_pushButton.setSizePolicy(sizePolicy)
        self.startServer_pushButton.setMinimumSize(QtCore.QSize(0, 0))
        self.startServer_pushButton.setObjectName("startServer_pushButton")
        self.gridLayout.addWidget(self.startServer_pushButton, 0, 0, 1, 1)
        self.stopServer_pushButton = QtGui.QPushButton(self.serverControl_groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stopServer_pushButton.sizePolicy().hasHeightForWidth())
        self.stopServer_pushButton.setSizePolicy(sizePolicy)
        self.stopServer_pushButton.setObjectName("stopServer_pushButton")
        self.gridLayout.addWidget(self.stopServer_pushButton, 1, 0, 1, 1)
        self.horizontalLayout_2.addWidget(self.serverControl_groupBox)
        self.information_groupBox = QtGui.QGroupBox(self.serverControl_tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.information_groupBox.sizePolicy().hasHeightForWidth())
        self.information_groupBox.setSizePolicy(sizePolicy)
        self.information_groupBox.setObjectName("information_groupBox")
        self.gridLayout_2 = QtGui.QGridLayout(self.information_groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.information_textBrowser = QtGui.QTextBrowser(self.information_groupBox)
        self.information_textBrowser.setEnabled(False)
        self.information_textBrowser.setObjectName("information_textBrowser")
        self.gridLayout_2.addWidget(self.information_textBrowser, 0, 0, 1, 1)
        self.horizontalLayout_2.addWidget(self.information_groupBox)
        self.Contrl_tabWidget.addTab(self.serverControl_tab, "")
        self.userControl_tab = QtGui.QWidget()
        self.userControl_tab.setObjectName("userControl_tab")
        self.verticalLayout = QtGui.QVBoxLayout(self.userControl_tab)
        self.verticalLayout.setObjectName("verticalLayout")
        self.userControl_toolBox = QtGui.QToolBox(self.userControl_tab)
        self.userControl_toolBox.setObjectName("userControl_toolBox")
        self.userMedia_page = QtGui.QWidget()
        self.userMedia_page.setGeometry(QtCore.QRect(0, 0, 430, 274))
        self.userMedia_page.setObjectName("userMedia_page")
        self.gridLayout_4 = QtGui.QGridLayout(self.userMedia_page)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.mysql_groupBox = QtGui.QGroupBox(self.userMedia_page)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.mysql_groupBox.sizePolicy().hasHeightForWidth())
        self.mysql_groupBox.setSizePolicy(sizePolicy)
        self.mysql_groupBox.setCheckable(True)
        self.mysql_groupBox.setChecked(False)
        self.mysql_groupBox.setObjectName("mysql_groupBox")
        self.gridLayout_3 = QtGui.QGridLayout(self.mysql_groupBox)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label = QtGui.QLabel(self.mysql_groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtGui.QLabel(self.mysql_groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 1, 0, 1, 1)
        self.label_3 = QtGui.QLabel(self.mysql_groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 2, 0, 1, 1)
        self.lineEdit_3 = QtGui.QLineEdit(self.mysql_groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_3.sizePolicy().hasHeightForWidth())
        self.lineEdit_3.setSizePolicy(sizePolicy)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout_3.addWidget(self.lineEdit_3, 1, 1, 1, 1)
        self.lineEdit = QtGui.QLineEdit(self.mysql_groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit.sizePolicy().hasHeightForWidth())
        self.lineEdit.setSizePolicy(sizePolicy)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout_3.addWidget(self.lineEdit, 0, 1, 1, 1)
        self.lineEdit_2 = QtGui.QLineEdit(self.mysql_groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_2.sizePolicy().hasHeightForWidth())
        self.lineEdit_2.setSizePolicy(sizePolicy)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout_3.addWidget(self.lineEdit_2, 2, 1, 1, 1)
        self.gridLayout_4.addWidget(self.mysql_groupBox, 0, 0, 1, 1)
        self.xml_groupBox = QtGui.QGroupBox(self.userMedia_page)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.xml_groupBox.sizePolicy().hasHeightForWidth())
        self.xml_groupBox.setSizePolicy(sizePolicy)
        self.xml_groupBox.setCheckable(True)
        self.xml_groupBox.setChecked(False)
        self.xml_groupBox.setObjectName("xml_groupBox")
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.xml_groupBox)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.xmlfile_label = QtGui.QLabel(self.xml_groupBox)
        self.xmlfile_label.setObjectName("xmlfile_label")
        self.horizontalLayout_5.addWidget(self.xmlfile_label)
        self.xml_lineEdit = QtGui.QLineEdit(self.xml_groupBox)
        self.xml_lineEdit.setObjectName("xml_lineEdit")
        self.horizontalLayout_5.addWidget(self.xml_lineEdit)
        self.openXml_pushButton = QtGui.QPushButton(self.xml_groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.openXml_pushButton.sizePolicy().hasHeightForWidth())
        self.openXml_pushButton.setSizePolicy(sizePolicy)
        self.openXml_pushButton.setObjectName("openXml_pushButton")
        self.horizontalLayout_5.addWidget(self.openXml_pushButton)
        self.gridLayout_4.addWidget(self.xml_groupBox, 1, 0, 1, 1)
        self.text_groupBox = QtGui.QGroupBox(self.userMedia_page)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.text_groupBox.sizePolicy().hasHeightForWidth())
        self.text_groupBox.setSizePolicy(sizePolicy)
        self.text_groupBox.setCheckable(True)
        self.text_groupBox.setChecked(False)
        self.text_groupBox.setObjectName("text_groupBox")
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.text_groupBox)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.textfile_label = QtGui.QLabel(self.text_groupBox)
        self.textfile_label.setObjectName("textfile_label")
        self.horizontalLayout_6.addWidget(self.textfile_label)
        self.text_lineEdit = QtGui.QLineEdit(self.text_groupBox)
        self.text_lineEdit.setObjectName("text_lineEdit")
        self.horizontalLayout_6.addWidget(self.text_lineEdit)
        self.openText_pushButton = QtGui.QPushButton(self.text_groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.openText_pushButton.sizePolicy().hasHeightForWidth())
        self.openText_pushButton.setSizePolicy(sizePolicy)
        self.openText_pushButton.setObjectName("openText_pushButton")
        self.horizontalLayout_6.addWidget(self.openText_pushButton)
        self.gridLayout_4.addWidget(self.text_groupBox, 2, 0, 1, 1)
        self.userControl_toolBox.addItem(self.userMedia_page, "")
        self.userInfo_page = QtGui.QWidget()
        self.userInfo_page.setGeometry(QtCore.QRect(0, 0, 96, 79))
        self.userInfo_page.setObjectName("userInfo_page")
        self.gridLayout_5 = QtGui.QGridLayout(self.userInfo_page)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.userInfo_tableView = QtGui.QTableView(self.userInfo_page)
        self.userInfo_tableView.setObjectName("userInfo_tableView")
        self.gridLayout_5.addWidget(self.userInfo_tableView, 0, 0, 1, 1)
        self.userControl_toolBox.addItem(self.userInfo_page, "")
        self.verticalLayout.addWidget(self.userControl_toolBox)
        self.Contrl_tabWidget.addTab(self.userControl_tab, "")
        self.systemCheck_tab = QtGui.QWidget()
        self.systemCheck_tab.setObjectName("systemCheck_tab")
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.systemCheck_tab)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.loginUsers_groupBox = QtGui.QGroupBox(self.systemCheck_tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.loginUsers_groupBox.sizePolicy().hasHeightForWidth())
        self.loginUsers_groupBox.setSizePolicy(sizePolicy)
        self.loginUsers_groupBox.setObjectName("loginUsers_groupBox")
        self.gridLayout_8 = QtGui.QGridLayout(self.loginUsers_groupBox)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.loginUsers_tableView = QtGui.QTableView(self.loginUsers_groupBox)
        self.loginUsers_tableView.setObjectName("loginUsers_tableView")
        self.gridLayout_8.addWidget(self.loginUsers_tableView, 0, 0, 1, 1)
        self.horizontalLayout_4.addWidget(self.loginUsers_groupBox)
        self.messageLogs_groupBox = QtGui.QGroupBox(self.systemCheck_tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.messageLogs_groupBox.sizePolicy().hasHeightForWidth())
        self.messageLogs_groupBox.setSizePolicy(sizePolicy)
        self.messageLogs_groupBox.setObjectName("messageLogs_groupBox")
        self.gridLayout_9 = QtGui.QGridLayout(self.messageLogs_groupBox)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.messageLogs_listView = QtGui.QListView(self.messageLogs_groupBox)
        self.messageLogs_listView.setObjectName("messageLogs_listView")
        self.gridLayout_9.addWidget(self.messageLogs_listView, 0, 0, 1, 1)
        self.horizontalLayout_4.addWidget(self.messageLogs_groupBox)
        self.Contrl_tabWidget.addTab(self.systemCheck_tab, "")
        self.horizontalLayout.addWidget(self.Contrl_tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 452, 18))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtGui.QMenu(self.menubar)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.menuFile.setFont(font)
        self.menuFile.setObjectName("menuFile")
        self.menuLanguage = QtGui.QMenu(self.menuFile)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.menuLanguage.setFont(font)
        self.menuLanguage.setObjectName("menuLanguage")
        self.menuHelp = QtGui.QMenu(self.menubar)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.menuHelp.setFont(font)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionAbout = QtGui.QAction(MainWindow)
        font = QtGui.QFont()
        self.actionAbout.setFont(font)
        self.actionAbout.setObjectName("actionAbout")
        self.actionExit = QtGui.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionSave_Config = QtGui.QAction(MainWindow)
        font = QtGui.QFont()
        self.actionSave_Config.setFont(font)
        self.actionSave_Config.setObjectName("actionSave_Config")
        self.actionLoad_Config = QtGui.QAction(MainWindow)
        font = QtGui.QFont()
        self.actionLoad_Config.setFont(font)
        self.actionLoad_Config.setObjectName("actionLoad_Config")
        self.actionEnglish = QtGui.QAction(MainWindow)
        font = QtGui.QFont()
        self.actionEnglish.setFont(font)
        self.actionEnglish.setObjectName("actionEnglish")
        self.actionChinese = QtGui.QAction(MainWindow)
        font = QtGui.QFont()
        self.actionChinese.setFont(font)
        self.actionChinese.setObjectName("actionChinese")
        self.menuLanguage.addAction(self.actionEnglish)
        self.menuLanguage.addAction(self.actionChinese)
        self.menuFile.addAction(self.actionLoad_Config)
        self.menuFile.addAction(self.actionSave_Config)
        self.menuFile.addAction(self.menuLanguage.menuAction())
        self.menuFile.addAction(self.actionExit)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.Contrl_tabWidget.setCurrentIndex(0)
        self.userControl_toolBox.setCurrentIndex(0)
        QtCore.QObject.connect(self.actionExit, QtCore.SIGNAL("activated()"), MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "xdIm Server Manager ", None, QtGui.QApplication.UnicodeUTF8))
        self.serverControl_groupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Server", None, QtGui.QApplication.UnicodeUTF8))
        self.startServer_pushButton.setText(QtGui.QApplication.translate("MainWindow", "Start Server", None, QtGui.QApplication.UnicodeUTF8))
        self.stopServer_pushButton.setText(QtGui.QApplication.translate("MainWindow", "Stop Server", None, QtGui.QApplication.UnicodeUTF8))
        self.information_groupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Information", None, QtGui.QApplication.UnicodeUTF8))
        self.Contrl_tabWidget.setTabText(self.Contrl_tabWidget.indexOf(self.serverControl_tab), QtGui.QApplication.translate("MainWindow", "Server Control", None, QtGui.QApplication.UnicodeUTF8))
        self.mysql_groupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Mysql", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "server:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "user:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "password:", None, QtGui.QApplication.UnicodeUTF8))
        self.xml_groupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Xml", None, QtGui.QApplication.UnicodeUTF8))
        self.xmlfile_label.setText(QtGui.QApplication.translate("MainWindow", "file:", None, QtGui.QApplication.UnicodeUTF8))
        self.openXml_pushButton.setText(QtGui.QApplication.translate("MainWindow", "open Xml", None, QtGui.QApplication.UnicodeUTF8))
        self.text_groupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Text", None, QtGui.QApplication.UnicodeUTF8))
        self.textfile_label.setText(QtGui.QApplication.translate("MainWindow", "file:", None, QtGui.QApplication.UnicodeUTF8))
        self.openText_pushButton.setText(QtGui.QApplication.translate("MainWindow", "open txt", None, QtGui.QApplication.UnicodeUTF8))
        self.userControl_toolBox.setItemText(self.userControl_toolBox.indexOf(self.userMedia_page), QtGui.QApplication.translate("MainWindow", "user visit media", None, QtGui.QApplication.UnicodeUTF8))
        self.userControl_toolBox.setItemText(self.userControl_toolBox.indexOf(self.userInfo_page), QtGui.QApplication.translate("MainWindow", "user infomation", None, QtGui.QApplication.UnicodeUTF8))
        self.Contrl_tabWidget.setTabText(self.Contrl_tabWidget.indexOf(self.userControl_tab), QtGui.QApplication.translate("MainWindow", "User Control", None, QtGui.QApplication.UnicodeUTF8))
        self.loginUsers_groupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Login users", None, QtGui.QApplication.UnicodeUTF8))
        self.messageLogs_groupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Message logs", None, QtGui.QApplication.UnicodeUTF8))
        self.Contrl_tabWidget.setTabText(self.Contrl_tabWidget.indexOf(self.systemCheck_tab), QtGui.QApplication.translate("MainWindow", "System Check", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuLanguage.setTitle(QtGui.QApplication.translate("MainWindow", "Language", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHelp.setTitle(QtGui.QApplication.translate("MainWindow", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout.setText(QtGui.QApplication.translate("MainWindow", "About", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setText(QtGui.QApplication.translate("MainWindow", "Exit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave_Config.setText(QtGui.QApplication.translate("MainWindow", "Save Config", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLoad_Config.setText(QtGui.QApplication.translate("MainWindow", "Load Config", None, QtGui.QApplication.UnicodeUTF8))
        self.actionEnglish.setText(QtGui.QApplication.translate("MainWindow", "English", None, QtGui.QApplication.UnicodeUTF8))
        self.actionChinese.setText(QtGui.QApplication.translate("MainWindow", "Chinese", None, QtGui.QApplication.UnicodeUTF8))

