# This file was automatically generated by pywxrc.
# -*- coding: UTF-8 -*-

import wx
import wx.xrc as xrc

__res = None

def get_resources():
    """ This function provides access to the XML resources in this module."""
    global __res
    if __res == None:
        __init_resources()
    return __res




class xrcserverManagerFrame(wx.Frame):
#!XRCED:begin-block:xrcserverManagerFrame.PreCreate
    def PreCreate(self, pre):
        """ This function is called during the class's initialization.
        
        Override it for custom setup before the window is created usually to
        set additional window styles using SetWindowStyle() and SetExtraStyle().
        """
        pass
        
#!XRCED:end-block:xrcserverManagerFrame.PreCreate

    def __init__(self, parent):
        # Two stage creation (see http://wiki.wxpython.org/index.cgi/TwoStageCreation)
        pre = wx.PreFrame()
        self.PreCreate(pre)
        get_resources().LoadOnFrame(pre, parent, "serverManagerFrame")
        self.PostCreate(pre)

        # Define variables for the controls, bind event handlers

        self.Bind(wx.EVT_COMBOBOX, self.OnCombobox_languageComboBox, id=xrc.XRCID('languageComboBox'))
        self.Bind(wx.EVT_TOGGLEBUTTON, self.OnTogglebutton_serverStartButton, id=xrc.XRCID('serverStartButton'))
        self.Bind(wx.EVT_TOGGLEBUTTON, self.OnTogglebutton_serverStopButton, id=xrc.XRCID('serverStopButton'))
        self.Bind(wx.EVT_RADIOBUTTON, self.OnRadiobutton_textUserRadioButton, id=xrc.XRCID('textUserRadioButton'))
        self.Bind(wx.EVT_BUTTON, self.OnButton_textUserButton, id=xrc.XRCID('textUserButton'))
        self.Bind(wx.EVT_RADIOBUTTON, self.OnRadiobutton_mysqlUserRadioButton, id=xrc.XRCID('mysqlUserRadioButton'))
        self.Bind(wx.EVT_BUTTON, self.OnButton_mysqlUserButton, id=xrc.XRCID('mysqlUserButton'))
        self.Bind(wx.EVT_RADIOBUTTON, self.OnRadiobutton_xmlUserRadioButton, id=xrc.XRCID('xmlUserRadioButton'))
        self.Bind(wx.EVT_BUTTON, self.OnButton_xmlUserButton, id=xrc.XRCID('xmlUserButton'))
        self.Bind(wx.EVT_BUTTON, self.OnButton_killUserButton, id=xrc.XRCID('killUserButton'))
        self.Bind(wx.EVT_BUTTON, self.OnButton_messageUserButton, id=xrc.XRCID('messageUserButton'))
        self.Bind(wx.EVT_BUTTON, self.OnButton_addUserButton, id=xrc.XRCID('addUserButton'))
        self.Bind(wx.EVT_BUTTON, self.OnButton_showAllUsersButton, id=xrc.XRCID('showAllUsersButton'))
        self.Bind(wx.EVT_NOTEBOOK_PAGE_CHANGED, self.OnNotebook_page_changed_mainNoteBook, id=xrc.XRCID('mainNoteBook'))
        self.Bind(wx.EVT_MENU, self.OnMenu_exitMenuItem, id=xrc.XRCID('exitMenuItem'))
        self.Bind(wx.EVT_MENU, self.OnMenu_aboutMenuItem, id=xrc.XRCID('aboutMenuItem'))

#!XRCED:begin-block:xrcserverManagerFrame.OnCombobox_languageComboBox
    def OnCombobox_languageComboBox(self, evt):
        # Replace with event handler code
        print "OnCombobox_languageComboBox()"
#!XRCED:end-block:xrcserverManagerFrame.OnCombobox_languageComboBox        

#!XRCED:begin-block:xrcserverManagerFrame.OnTogglebutton_serverStartButton
    def OnTogglebutton_serverStartButton(self, evt):
        # Replace with event handler code
        print "OnTogglebutton_serverStartButton()"
#!XRCED:end-block:xrcserverManagerFrame.OnTogglebutton_serverStartButton        

#!XRCED:begin-block:xrcserverManagerFrame.OnTogglebutton_serverStopButton
    def OnTogglebutton_serverStopButton(self, evt):
        # Replace with event handler code
        print "OnTogglebutton_serverStopButton()"
#!XRCED:end-block:xrcserverManagerFrame.OnTogglebutton_serverStopButton        

#!XRCED:begin-block:xrcserverManagerFrame.OnRadiobutton_textUserRadioButton
    def OnRadiobutton_textUserRadioButton(self, evt):
        # Replace with event handler code
        print "OnRadiobutton_textUserRadioButton()"
#!XRCED:end-block:xrcserverManagerFrame.OnRadiobutton_textUserRadioButton        

#!XRCED:begin-block:xrcserverManagerFrame.OnButton_textUserButton
    def OnButton_textUserButton(self, evt):
        # Replace with event handler code
        print "OnButton_textUserButton()"
#!XRCED:end-block:xrcserverManagerFrame.OnButton_textUserButton        

#!XRCED:begin-block:xrcserverManagerFrame.OnRadiobutton_mysqlUserRadioButton
    def OnRadiobutton_mysqlUserRadioButton(self, evt):
        # Replace with event handler code
        print "OnRadiobutton_mysqlUserRadioButton()"
#!XRCED:end-block:xrcserverManagerFrame.OnRadiobutton_mysqlUserRadioButton        

#!XRCED:begin-block:xrcserverManagerFrame.OnButton_mysqlUserButton
    def OnButton_mysqlUserButton(self, evt):
        # Replace with event handler code
        print "OnButton_mysqlUserButton()"
#!XRCED:end-block:xrcserverManagerFrame.OnButton_mysqlUserButton        

#!XRCED:begin-block:xrcserverManagerFrame.OnRadiobutton_xmlUserRadioButton
    def OnRadiobutton_xmlUserRadioButton(self, evt):
        # Replace with event handler code
        print "OnRadiobutton_xmlUserRadioButton()"
#!XRCED:end-block:xrcserverManagerFrame.OnRadiobutton_xmlUserRadioButton        

#!XRCED:begin-block:xrcserverManagerFrame.OnButton_xmlUserButton
    def OnButton_xmlUserButton(self, evt):
        # Replace with event handler code
        print "OnButton_xmlUserButton()"
#!XRCED:end-block:xrcserverManagerFrame.OnButton_xmlUserButton        

#!XRCED:begin-block:xrcserverManagerFrame.OnButton_killUserButton
    def OnButton_killUserButton(self, evt):
        # Replace with event handler code
        print "OnButton_killUserButton()"
#!XRCED:end-block:xrcserverManagerFrame.OnButton_killUserButton        

#!XRCED:begin-block:xrcserverManagerFrame.OnButton_messageUserButton
    def OnButton_messageUserButton(self, evt):
        # Replace with event handler code
        print "OnButton_messageUserButton()"
#!XRCED:end-block:xrcserverManagerFrame.OnButton_messageUserButton        

#!XRCED:begin-block:xrcserverManagerFrame.OnButton_addUserButton
    def OnButton_addUserButton(self, evt):
        # Replace with event handler code
        print "OnButton_addUserButton()"
#!XRCED:end-block:xrcserverManagerFrame.OnButton_addUserButton        

#!XRCED:begin-block:xrcserverManagerFrame.OnButton_showAllUsersButton
    def OnButton_showAllUsersButton(self, evt):
        # Replace with event handler code
        print "OnButton_showAllUsersButton()"
#!XRCED:end-block:xrcserverManagerFrame.OnButton_showAllUsersButton        

#!XRCED:begin-block:xrcserverManagerFrame.OnNotebook_page_changed_mainNoteBook
    def OnNotebook_page_changed_mainNoteBook(self, evt):
        # Replace with event handler code
        print "OnNotebook_page_changed_mainNoteBook()"
#!XRCED:end-block:xrcserverManagerFrame.OnNotebook_page_changed_mainNoteBook        

#!XRCED:begin-block:xrcserverManagerFrame.OnMenu_exitMenuItem
    def OnMenu_exitMenuItem(self, evt):
        # Replace with event handler code
        print "OnMenu_exitMenuItem()"
#!XRCED:end-block:xrcserverManagerFrame.OnMenu_exitMenuItem        

#!XRCED:begin-block:xrcserverManagerFrame.OnMenu_aboutMenuItem
    def OnMenu_aboutMenuItem(self, evt):
        # Replace with event handler code
        print "OnMenu_aboutMenuItem()"
#!XRCED:end-block:xrcserverManagerFrame.OnMenu_aboutMenuItem        




# ------------------------ Resource data ----------------------

def __init_resources():
    global __res
    __res = xrc.EmptyXmlResource()

    wx.FileSystem.AddHandler(wx.MemoryFSHandler())

    serverManager_xrc = '''\
<?xml version="1.0" ?><resource>
  <object class="wxFrame" name="serverManagerFrame">
    <object class="wxPanel" name="mainPanel">
      <object class="wxBoxSizer">
        <object class="sizeritem">
          <object class="wxNotebook" name="mainNoteBook">
            <object class="notebookpage">
              <object class="wxPanel" name="serverControlPanel">
                <object class="wxGridBagSizer">
                  <object class="sizeritem">
                    <object class="wxComboBox" name="languageComboBox">
                      <content>
                        <item>Chinese</item>
                        <item>English</item>
                      </content>
                      <value>Chinese</value>
                      <XRCED>
                        <events>EVT_COMBOBOX</events>
                      </XRCED>
                    </object>
                    <flag>wxALIGN_CENTRE</flag>
                    <cellpos>1,1</cellpos>
                  </object>
                  <object class="sizeritem">
                    <object class="wxToggleButton" name="serverStartButton">
                      <label>Start Server</label>
                      <XRCED>
                        <events>EVT_TOGGLEBUTTON</events>
                      </XRCED>
                    </object>
                    <flag>wxALIGN_CENTRE</flag>
                    <cellpos>2,1</cellpos>
                  </object>
                  <object class="sizeritem">
                    <object class="wxToggleButton" name="serverStopButton">
                      <label>Stop Server</label>
                      <XRCED>
                        <events>EVT_TOGGLEBUTTON</events>
                      </XRCED>
                    </object>
                    <flag>wxALIGN_CENTRE</flag>
                    <cellpos>3,1</cellpos>
                  </object>
                  <growablecols>1</growablecols>
                  <growablerows>1,2,3</growablerows>
                </object>
              </object>
              <label>Server Control</label>
            </object>
            <object class="notebookpage">
              <object class="wxPanel" name="userControlPanel">
                <object class="wxBoxSizer">
                  <orient>wxVERTICAL</orient>
                  <object class="sizeritem">
                    <object class="wxPanel" name="textUserPanel">
                      <object class="wxGridBagSizer">
                        <object class="sizeritem">
                          <object class="wxRadioButton" name="textUserRadioButton">
                            <label>use txt file control user</label>
                            <XRCED>
                              <events>EVT_RADIOBUTTON</events>
                            </XRCED>
                          </object>
                          <option>1</option>
                          <flag>wxALL|wxALIGN_LEFT|wxALIGN_CENTRE_VERTICAL</flag>
                          <border>5</border>
                          <cellpos>1,2</cellpos>
                        </object>
                        <object class="sizeritem">
                          <object class="wxButton" name="textUserButton">
                            <label>Open txt</label>
                            <XRCED>
                              <events>EVT_BUTTON</events>
                            </XRCED>
                          </object>
                          <option>1</option>
                          <flag>wxALL|wxALIGN_CENTRE</flag>
                          <border>10</border>
                          <cellpos>1,3</cellpos>
                        </object>
                        <object class="sizeritem">
                          <object class="wxRadioButton" name="mysqlUserRadioButton">
                            <label>use mysql database control user</label>
                            <XRCED>
                              <events>EVT_RADIOBUTTON</events>
                            </XRCED>
                          </object>
                          <option>1</option>
                          <flag>wxALL|wxALIGN_LEFT|wxALIGN_CENTRE_VERTICAL</flag>
                          <border>5</border>
                          <cellpos>2,2</cellpos>
                        </object>
                        <object class="sizeritem">
                          <object class="wxButton" name="mysqlUserButton">
                            <label>Control</label>
                            <XRCED>
                              <events>EVT_BUTTON</events>
                            </XRCED>
                          </object>
                          <option>1</option>
                          <flag>wxALL|wxALIGN_CENTRE</flag>
                          <border>10</border>
                          <cellpos>2,3</cellpos>
                        </object>
                        <object class="sizeritem">
                          <object class="wxRadioButton" name="xmlUserRadioButton">
                            <label>use xml file control user</label>
                            <XRCED>
                              <events>EVT_RADIOBUTTON</events>
                            </XRCED>
                          </object>
                          <option>1</option>
                          <flag>wxALL|wxALIGN_LEFT|wxALIGN_CENTRE_VERTICAL</flag>
                          <border>5</border>
                          <cellpos>3,2</cellpos>
                        </object>
                        <object class="sizeritem">
                          <object class="wxButton" name="xmlUserButton">
                            <label>Open xml</label>
                            <XRCED>
                              <events>EVT_BUTTON</events>
                            </XRCED>
                          </object>
                          <option>1</option>
                          <flag>wxALL|wxALIGN_CENTRE</flag>
                          <border>10</border>
                          <cellpos>3,3</cellpos>
                        </object>
                        <vgap>4</vgap>
                        <hgap>4</hgap>
                        <growablecols>1,2,3</growablecols>
                        <growablerows>1,2,3</growablerows>
                      </object>
                    </object>
                    <option>1</option>
                    <flag>wxEXPAND</flag>
                  </object>
                </object>
              </object>
              <label>User Control</label>
            </object>
            <object class="notebookpage">
              <object class="wxPanel" name="systemCheckPanel">
                <object class="wxGridBagSizer">
                  <object class="sizeritem">
                    <object class="wxPanel" name="userGrid1Panel">
                      <object class="wxBoxSizer">
                        <orient>wxVERTICAL</orient>
                        <object class="sizeritem">
                          <object class="wxGrid" name="userGrid"/>
                          <option>1</option>
                          <flag>wxEXPAND</flag>
                          <border>2</border>
                        </object>
                        <object class="sizeritem">
                          <object class="wxTextCtrl" name="userTextCtrl">
                            <style>wxTE_MULTILINE</style>
                          </object>
                          <option>1</option>
                          <flag>wxEXPAND</flag>
                          <border>2</border>
                        </object>
                      </object>
                    </object>
                    <option>1</option>
                    <flag>wxEXPAND</flag>
                    <cellpos>0,0</cellpos>
                  </object>
                  <growablecols>0</growablecols>
                  <growablerows>0</growablerows>
                  <object class="sizeritem">
                    <object class="wxPanel" name="userGrid2Panel">
                      <object class="wxBoxSizer">
                        <orient>wxVERTICAL</orient>
                        <object class="sizeritem">
                          <object class="wxButton" name="killUserButton">
                            <label>Kill User</label>
                            <XRCED>
                              <events>EVT_BUTTON</events>
                            </XRCED>
                          </object>
                          <flag>wxEXPAND</flag>
                        </object>
                        <object class="sizeritem">
                          <object class="wxButton" name="messageUserButton">
                            <label>Message User</label>
                            <XRCED>
                              <events>EVT_BUTTON</events>
                            </XRCED>
                          </object>
                          <flag>wxEXPAND</flag>
                        </object>
                        <object class="sizeritem">
                          <object class="wxButton" name="addUserButton">
                            <label>Add user</label>
                            <XRCED>
                              <events>EVT_BUTTON</events>
                            </XRCED>
                          </object>
                          <flag>wxEXPAND</flag>
                        </object>
                        <object class="sizeritem">
                          <object class="wxButton" name="showAllUsersButton">
                            <label>Show all users</label>
                            <XRCED>
                              <events>EVT_BUTTON</events>
                            </XRCED>
                          </object>
                          <flag>wxEXPAND</flag>
                        </object>
                      </object>
                    </object>
                    <flag>wxEXPAND</flag>
                    <cellpos>0,1</cellpos>
                  </object>
                </object>
              </object>
              <label>System Check</label>
            </object>
            <XRCED>
              <events>EVT_NOTEBOOK_PAGE_CHANGED</events>
            </XRCED>
          </object>
          <option>1</option>
          <flag>wxEXPAND</flag>
        </object>
        <orient>wxHORIZONTAL</orient>
      </object>
    </object>
    <object class="wxStatusBar" name="mainStatusBar"/>
    <object class="wxMenuBar" name="mainMenuBar">
      <object class="wxMenu" name="fileMenu">
        <object class="wxMenuItem" name="exitMenuItem">
          <label>Exit</label>
          <XRCED>
            <events>EVT_MENU</events>
          </XRCED>
        </object>
        <label>File</label>
      </object>
      <object class="wxMenu" name="helpMenu">
        <object class="wxMenuItem" name="aboutMenuItem">
          <label>About</label>
          <XRCED>
            <events>EVT_MENU</events>
          </XRCED>
        </object>
        <label>Help</label>
      </object>
    </object>
    <title>xdIm server Manager</title>
    <centered>1</centered>
  </object>
</resource>'''

    wx.MemoryFSHandler.AddFile('XRC/serverManager/serverManager_xrc', serverManager_xrc)
    __res.Load('memory:XRC/serverManager/serverManager_xrc')


# ----------------------- Gettext strings ---------------------

def __gettext_strings():
    # This is a dummy function that lists all the strings that are used in
    # the XRC file in the _("a string") format to be recognized by GNU
    # gettext utilities (specificaly the xgettext utility) and the
    # mki18n.py script.  For more information see:
    # http://wiki.wxpython.org/index.cgi/Internationalization 
    
    def _(str): pass
    
    _("Chinese")
    _("English")
    _("Chinese")
    _("Start Server")
    _("Stop Server")
    _("Server Control")
    _("use txt file control user")
    _("Open txt")
    _("use mysql database control user")
    _("Control")
    _("use xml file control user")
    _("Open xml")
    _("User Control")
    _("Kill User")
    _("Message User")
    _("Add user")
    _("Show all users")
    _("System Check")
    _("Exit")
    _("File")
    _("About")
    _("Help")
    _("xdIm server Manager")

