# This file was automatically generated by pywxrc.
# -*- coding: UTF-8 -*-

import wx
import wx.xrc as xrc

__res = None

def get_resources():
    """ This function provides access to the XML resources in this module."""
    global __res
    if __res == None:
        __init_resources()
    return __res




class xrcmainFrame(wx.Frame):
#!XRCED:begin-block:xrcmainFrame.PreCreate
    def PreCreate(self, pre):
        """ This function is called during the class's initialization.
        
        Override it for custom setup before the window is created usually to
        set additional window styles using SetWindowStyle() and SetExtraStyle().
        """
        pass
        
#!XRCED:end-block:xrcmainFrame.PreCreate

    def __init__(self, parent):
        # Two stage creation (see http://wiki.wxpython.org/index.cgi/TwoStageCreation)
        pre = wx.PreFrame()
        self.PreCreate(pre)
        get_resources().LoadOnFrame(pre, parent, "mainFrame")
        self.PostCreate(pre)

        # Define variables for the controls, bind event handlers

        self.Bind(wx.EVT_MENU, self.OnMenu_loginMenuItem, id=xrc.XRCID('loginMenuItem'))
        self.Bind(wx.EVT_MENU, self.OnMenu_logoutMenuItem, id=xrc.XRCID('logoutMenuItem'))
        self.Bind(wx.EVT_MENU, self.OnMenu_addFriendMenuItem, id=xrc.XRCID('addFriendMenuItem'))
        self.Bind(wx.EVT_MENU, self.OnMenu_deleteFriendMenuItem, id=xrc.XRCID('deleteFriendMenuItem'))
        self.Bind(wx.EVT_MENU, self.OnMenu_aboutMenuItem, id=xrc.XRCID('aboutMenuItem'))
        self.Bind(wx.EVT_CLOSE, self.OnClose)

#!XRCED:begin-block:xrcmainFrame.OnMenu_loginMenuItem
    def OnMenu_loginMenuItem(self, evt):
        # Replace with event handler code
        print "OnMenu_loginMenuItem()"
#!XRCED:end-block:xrcmainFrame.OnMenu_loginMenuItem        

#!XRCED:begin-block:xrcmainFrame.OnMenu_logoutMenuItem
    def OnMenu_logoutMenuItem(self, evt):
        # Replace with event handler code
        print "OnMenu_logoutMenuItem()"
#!XRCED:end-block:xrcmainFrame.OnMenu_logoutMenuItem        

#!XRCED:begin-block:xrcmainFrame.OnMenu_addFriendMenuItem
    def OnMenu_addFriendMenuItem(self, evt):
        # Replace with event handler code
        print "OnMenu_addFriendMenuItem()"
#!XRCED:end-block:xrcmainFrame.OnMenu_addFriendMenuItem        

#!XRCED:begin-block:xrcmainFrame.OnMenu_deleteFriendMenuItem
    def OnMenu_deleteFriendMenuItem(self, evt):
        # Replace with event handler code
        print "OnMenu_deleteFriendMenuItem()"
#!XRCED:end-block:xrcmainFrame.OnMenu_deleteFriendMenuItem        

#!XRCED:begin-block:xrcmainFrame.OnMenu_aboutMenuItem
    def OnMenu_aboutMenuItem(self, evt):
        # Replace with event handler code
        print "OnMenu_aboutMenuItem()"
#!XRCED:end-block:xrcmainFrame.OnMenu_aboutMenuItem        

#!XRCED:begin-block:xrcmainFrame.OnClose
    def OnClose(self, evt):
        # Replace with event handler code
        print "OnClose()"
#!XRCED:end-block:xrcmainFrame.OnClose        




# ------------------------ Resource data ----------------------

def __init_resources():
    global __res
    __res = xrc.EmptyXmlResource()

    wx.FileSystem.AddHandler(wx.MemoryFSHandler())

    im_xrc = '''\
<?xml version="1.0" ?><resource>
  <object class="wxFrame" name="mainFrame">
    <object class="wxMenuBar" name="mainMenuBar">
      <object class="wxMenu" name="FileMenu">
        <object class="wxMenuItem" name="loginMenuItem">
          <label>login</label>
          <XRCED>
            <events>EVT_MENU</events>
          </XRCED>
        </object>
        <object class="wxMenuItem" name="logoutMenuItem">
          <label>logout</label>
          <XRCED>
            <events>EVT_MENU</events>
          </XRCED>
        </object>
        <label>File</label>
      </object>
      <object class="wxMenu" name="operateMenu">
        <label>operate</label>
        <object class="wxMenuItem" name="addFriendMenuItem">
          <label>add Friend</label>
          <XRCED>
            <events>EVT_MENU</events>
          </XRCED>
        </object>
        <object class="wxMenuItem" name="deleteFriendMenuItem">
          <label>delete Friend</label>
          <XRCED>
            <events>EVT_MENU</events>
          </XRCED>
        </object>
      </object>
      <object class="wxMenu" name="helpMenu">
        <label>help</label>
        <object class="wxMenuItem" name="aboutMenuItem">
          <label>about</label>
          <XRCED>
            <events>EVT_MENU</events>
          </XRCED>
        </object>
      </object>
    </object>
    <object class="wxBoxSizer">
      <orient>wxVERTICAL</orient>
    </object>
    <title>Im</title>
    <centered>1</centered>
    <XRCED>
      <events>EVT_CLOSE</events>
    </XRCED>
  </object>
</resource>'''

    wx.MemoryFSHandler.AddFile('XRC/im/im_xrc', im_xrc)
    __res.Load('memory:XRC/im/im_xrc')


# ----------------------- Gettext strings ---------------------

def __gettext_strings():
    # This is a dummy function that lists all the strings that are used in
    # the XRC file in the _("a string") format to be recognized by GNU
    # gettext utilities (specificaly the xgettext utility) and the
    # mki18n.py script.  For more information see:
    # http://wiki.wxpython.org/index.cgi/Internationalization 
    
    def _(str): pass
    
    _("login")
    _("logout")
    _("File")
    _("operate")
    _("add Friend")
    _("delete Friend")
    _("help")
    _("about")
    _("Im")

