# This file was automatically generated by pywxrc.
# -*- coding: UTF-8 -*-

import wx
import wx.xrc as xrc

__res = None

def get_resources():
    """ This function provides access to the XML resources in this module."""
    global __res
    if __res == None:
        __init_resources()
    return __res




class xrcmainPanel(wx.Panel):
#!XRCED:begin-block:xrcmainPanel.PreCreate
    def PreCreate(self, pre):
        """ This function is called during the class's initialization.
        
        Override it for custom setup before the window is created usually to
        set additional window styles using SetWindowStyle() and SetExtraStyle().
        """
        pass
        
#!XRCED:end-block:xrcmainPanel.PreCreate

    def __init__(self, parent):
        # Two stage creation (see http://wiki.wxpython.org/index.cgi/TwoStageCreation)
        pre = wx.PrePanel()
        self.PreCreate(pre)
        get_resources().LoadOnPanel(pre, parent, "mainPanel")
        self.PostCreate(pre)

        # Define variables for the controls, bind event handlers

        self.Bind(wx.EVT_BUTTON, self.OnButton_okButton, id=xrc.XRCID('okButton'))
        self.Bind(wx.EVT_BUTTON, self.OnButton_cancelButton, id=xrc.XRCID('cancelButton'))

#!XRCED:begin-block:xrcmainPanel.OnButton_okButton
    def OnButton_okButton(self, evt):
        # Replace with event handler code
        print "OnButton_okButton()"
#!XRCED:end-block:xrcmainPanel.OnButton_okButton        

#!XRCED:begin-block:xrcmainPanel.OnButton_cancelButton
    def OnButton_cancelButton(self, evt):
        # Replace with event handler code
        print "OnButton_cancelButton()"
#!XRCED:end-block:xrcmainPanel.OnButton_cancelButton        




# ------------------------ Resource data ----------------------

def __init_resources():
    global __res
    __res = xrc.EmptyXmlResource()

    wx.FileSystem.AddHandler(wx.MemoryFSHandler())

    loginPanel_xrc = '''\
<?xml version="1.0" ?><resource>
  <object class="wxPanel" name="mainPanel">
    <object class="wxGridBagSizer">
      <object class="sizeritem">
        <object class="wxStaticText" name="serverStaticText">
          <label>server</label>
        </object>
        <option>2</option>
        <flag>wxALL|wxALIGN_LEFT|wxADJUST_MINSIZE</flag>
        <border>5</border>
        <cellpos>1,1</cellpos>
      </object>
      <object class="sizeritem">
        <object class="wxComboBox" name="serverComboBox"/>
        <option>1</option>
        <flag>wxALL|wxGROW|wxALIGN_LEFT|wxADJUST_MINSIZE</flag>
        <border>5</border>
        <cellpos>1,2</cellpos>
        <cellspan>1,2</cellspan>
      </object>
      <object class="sizeritem">
        <object class="wxStaticText" name="userStaticText">
          <label>user</label>
        </object>
        <option>2</option>
        <flag>wxALL|wxALIGN_LEFT|wxADJUST_MINSIZE</flag>
        <border>5</border>
        <cellpos>2,1</cellpos>
      </object>
      <object class="sizeritem">
        <object class="wxComboBox" name="userComboBox"/>
        <option>1</option>
        <flag>wxALL|wxGROW|wxALIGN_LEFT|wxADJUST_MINSIZE</flag>
        <border>5</border>
        <cellpos>2,2</cellpos>
        <cellspan>1,2</cellspan>
      </object>
      <object class="sizeritem">
        <object class="wxStaticText" name="passwordStaticText">
          <label>password</label>
        </object>
        <option>2</option>
        <flag>wxALL|wxALIGN_LEFT|wxADJUST_MINSIZE</flag>
        <border>5</border>
        <cellpos>3,1</cellpos>
      </object>
      <object class="sizeritem">
        <object class="wxBoxSizer">
          <object class="sizeritem">
            <object class="wxTextCtrl" name="passwordTextCtrl">
              <style>wxTE_PASSWORD</style>
            </object>
            <option>0</option>
            <flag>wxEXPAND</flag>
          </object>
          <orient>wxVERTICAL</orient>
        </object>
        <option>1</option>
        <flag>wxALL|wxEXPAND</flag>
        <border>5</border>
        <cellpos>3,2</cellpos>
        <cellspan>1,2</cellspan>
      </object>
      <object class="sizeritem">
        <object class="wxButton" name="okButton">
          <label>ok</label>
          <XRCED>
            <events>EVT_BUTTON</events>
          </XRCED>
        </object>
        <option>1</option>
        <flag>wxALL|wxALIGN_LEFT|wxALIGN_CENTRE_VERTICAL|wxADJUST_MINSIZE</flag>
        <border>5</border>
        <cellpos>4,1</cellpos>
      </object>
      <object class="sizeritem">
        <object class="wxButton" name="cancelButton">
          <label>cancel</label>
          <XRCED>
            <events>EVT_BUTTON</events>
          </XRCED>
        </object>
        <option>1</option>
        <flag>wxALL|wxALIGN_LEFT|wxALIGN_CENTRE_VERTICAL|wxADJUST_MINSIZE</flag>
        <border>5</border>
        <cellpos>4,2</cellpos>
      </object>
      <vgap>4</vgap>
      <hgap>4</hgap>
      <growablecols>1,2,3</growablecols>
      <growablerows>1,2,3</growablerows>
    </object>
    <style>wxSTATIC_BORDER|wxTAB_TRAVERSAL</style>
  </object>
</resource>'''

    wx.MemoryFSHandler.AddFile('XRC/loginPanel/loginPanel_xrc', loginPanel_xrc)
    __res.Load('memory:XRC/loginPanel/loginPanel_xrc')


# ----------------------- Gettext strings ---------------------

def __gettext_strings():
    # This is a dummy function that lists all the strings that are used in
    # the XRC file in the _("a string") format to be recognized by GNU
    # gettext utilities (specificaly the xgettext utility) and the
    # mki18n.py script.  For more information see:
    # http://wiki.wxpython.org/index.cgi/Internationalization 
    
    def _(str): pass
    
    _("server")
    _("user")
    _("password")
    _("ok")
    _("cancel")

