# This file was automatically generated by pywxrc.
# -*- coding: UTF-8 -*-

import wx
import wx.xrc as xrc

__res = None

def get_resources():
    """ This function provides access to the XML resources in this module."""
    global __res
    if __res == None:
        __init_resources()
    return __res




class xrcmainPanel(wx.Panel):
#!XRCED:begin-block:xrcmainPanel.PreCreate
    def PreCreate(self, pre):
        """ This function is called during the class's initialization.
        
        Override it for custom setup before the window is created usually to
        set additional window styles using SetWindowStyle() and SetExtraStyle().
        """
        pass
        
#!XRCED:end-block:xrcmainPanel.PreCreate

    def __init__(self, parent):
        # Two stage creation (see http://wiki.wxpython.org/index.cgi/TwoStageCreation)
        pre = wx.PrePanel()
        self.PreCreate(pre)
        get_resources().LoadOnPanel(pre, parent, "mainPanel")
        self.PostCreate(pre)

        # Define variables for the controls, bind event handlers

        self.Bind(wx.EVT_TREE_ITEM_ACTIVATED, self.OnTree_item_activated_linkmanTreeCtrl, id=xrc.XRCID('linkmanTreeCtrl'))
        self.Bind(wx.EVT_TREE_ITEM_MENU, self.OnTree_item_menu_linkmanTreeCtrl, id=xrc.XRCID('linkmanTreeCtrl'))

#!XRCED:begin-block:xrcmainPanel.OnTree_item_activated_linkmanTreeCtrl
    def OnTree_item_activated_linkmanTreeCtrl(self, evt):
        # Replace with event handler code
        print "OnTree_item_activated_linkmanTreeCtrl()"
#!XRCED:end-block:xrcmainPanel.OnTree_item_activated_linkmanTreeCtrl        

#!XRCED:begin-block:xrcmainPanel.OnTree_item_menu_linkmanTreeCtrl
    def OnTree_item_menu_linkmanTreeCtrl(self, evt):
        # Replace with event handler code
        print "OnTree_item_menu_linkmanTreeCtrl()"
#!XRCED:end-block:xrcmainPanel.OnTree_item_menu_linkmanTreeCtrl        




# ------------------------ Resource data ----------------------

def __init_resources():
    global __res
    __res = xrc.EmptyXmlResource()

    wx.FileSystem.AddHandler(wx.MemoryFSHandler())

    mainPanel_xrc = '''\
<?xml version="1.0" ?><resource>
  <object class="wxPanel" name="mainPanel">
    <object class="wxBoxSizer">
      <orient>wxVERTICAL</orient>
      <object class="sizeritem">
        <object class="wxNotebook" name="mainNotebook">
          <object class="notebookpage">
            <object class="wxPanel" name="linkmanPanel">
              <object class="wxBoxSizer">
                <orient>wxVERTICAL</orient>
                <object class="sizeritem">
                  <object class="wxTreeCtrl" name="linkmanTreeCtrl">
                    <XRCED>
                      <events>EVT_TREE_ITEM_ACTIVATED|EVT_TREE_ITEM_MENU</events>
                    </XRCED>
                  </object>
                  <option>1</option>
                  <flag>wxEXPAND</flag>
                </object>
              </object>
            </object>
            <label>linkman</label>
          </object>
          <object class="notebookpage">
            <object class="wxPanel" name="groupPanel">
              <object class="wxBoxSizer">
                <orient>wxVERTICAL</orient>
                <object class="sizeritem">
                  <object class="wxTreeCtrl" name="groupTreeCtrl"/>
                  <option>1</option>
                  <flag>wxEXPAND</flag>
                </object>
              </object>
            </object>
            <label>group</label>
          </object>
        </object>
        <option>1</option>
        <flag>wxEXPAND</flag>
        <border>0</border>
        <minsize>200,400</minsize>
      </object>
    </object>
  </object>
</resource>'''

    wx.MemoryFSHandler.AddFile('XRC/mainPanel/mainPanel_xrc', mainPanel_xrc)
    __res.Load('memory:XRC/mainPanel/mainPanel_xrc')


# ----------------------- Gettext strings ---------------------

def __gettext_strings():
    # This is a dummy function that lists all the strings that are used in
    # the XRC file in the _("a string") format to be recognized by GNU
    # gettext utilities (specificaly the xgettext utility) and the
    # mki18n.py script.  For more information see:
    # http://wiki.wxpython.org/index.cgi/Internationalization 
    
    def _(str): pass
    
    _("linkman")
    _("group")

