# coding=utf-8
# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='messageProtocol.proto',
  package='messageProtocol',
  serialized_pb='\n\x15messageProtocol.proto\x12\x0fmessageProtocol\"\xb9\x01\n\tcommunion\x12\x0f\n\x07srcName\x18\x01 \x02(\t\x12\x0f\n\x07\x64stName\x18\x02 \x02(\t\x12;\n\x0bmessageFlag\x18\x03 \x02(\x0e\x32&.messageProtocol.communion.messageType\x12\x0f\n\x07message\x18\x04 \x02(\t\"<\n\x0bmessageType\x12\x10\n\x0cuserPassword\x10\x00\x12\x0e\n\nfriendList\x10\x01\x12\x0b\n\x07\x63ontent\x10\x02\"\x8a\x02\n\x0cuserPassword\x12\x0c\n\x04user\x18\x01 \x02(\t\x12\x10\n\x08password\x18\x02 \x02(\t\x12>\n\x0bmessageFlag\x18\x03 \x02(\x0e\x32).messageProtocol.userPassword.messageType\x12;\n\x07message\x18\x04 \x01(\x0e\x32*.messageProtocol.userPassword.messageValue\"*\n\x0bmessageType\x12\x0b\n\x07request\x10\x00\x12\x0e\n\nresponsion\x10\x01\"1\n\x0cmessageValue\x12\t\n\x05login\x10\x00\x12\n\n\x06sucess\x10\x01\x12\n\n\x06\x66\x61iled\x10\x02\"i\n\x06\x46riend\x12\x0c\n\x04user\x18\x01 \x02(\t\x12.\n\x06status\x18\x02 \x02(\x0e\x32\x1e.messageProtocol.Friend.Status\"!\n\x06Status\x12\n\n\x06online\x10\x00\x12\x0b\n\x07outline\x10\x01\"\x92\x01\n\nfriendlist\x12<\n\x0bmessageFlag\x18\x01 \x02(\x0e\x32\'.messageProtocol.friendlist.messageType\x12\x0e\n\x06\x66riend\x18\x02 \x03(\t\"6\n\x0bmessageType\x12\x0b\n\x07request\x10\x00\x12\x0e\n\nresponsion\x10\x01\x12\n\n\x06\x61\x63tive\x10\x02')



_COMMUNION_MESSAGETYPE = descriptor.EnumDescriptor(
  name='messageType',
  full_name='messageProtocol.communion.messageType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    descriptor.EnumValueDescriptor(
      name='userPassword', index=0, number=0,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='friendList', index=1, number=1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='content', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=168,
  serialized_end=228,
)

_USERPASSWORD_MESSAGETYPE = descriptor.EnumDescriptor(
  name='messageType',
  full_name='messageProtocol.userPassword.messageType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    descriptor.EnumValueDescriptor(
      name='request', index=0, number=0,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='responsion', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=404,
  serialized_end=446,
)

_USERPASSWORD_MESSAGEVALUE = descriptor.EnumDescriptor(
  name='messageValue',
  full_name='messageProtocol.userPassword.messageValue',
  filename=None,
  file=DESCRIPTOR,
  values=[
    descriptor.EnumValueDescriptor(
      name='login', index=0, number=0,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='sucess', index=1, number=1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='failed', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=448,
  serialized_end=497,
)

_FRIEND_STATUS = descriptor.EnumDescriptor(
  name='Status',
  full_name='messageProtocol.Friend.Status',
  filename=None,
  file=DESCRIPTOR,
  values=[
    descriptor.EnumValueDescriptor(
      name='online', index=0, number=0,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='outline', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=571,
  serialized_end=604,
)

_FRIENDLIST_MESSAGETYPE = descriptor.EnumDescriptor(
  name='messageType',
  full_name='messageProtocol.friendlist.messageType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    descriptor.EnumValueDescriptor(
      name='request', index=0, number=0,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='responsion', index=1, number=1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='active', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=699,
  serialized_end=753,
)


_COMMUNION = descriptor.Descriptor(
  name='communion',
  full_name='messageProtocol.communion',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='srcName', full_name='messageProtocol.communion.srcName', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='dstName', full_name='messageProtocol.communion.dstName', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='messageFlag', full_name='messageProtocol.communion.messageFlag', index=2,
      number=3, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='message', full_name='messageProtocol.communion.message', index=3,
      number=4, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _COMMUNION_MESSAGETYPE,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=43,
  serialized_end=228,
)


_USERPASSWORD = descriptor.Descriptor(
  name='userPassword',
  full_name='messageProtocol.userPassword',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='user', full_name='messageProtocol.userPassword.user', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='password', full_name='messageProtocol.userPassword.password', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='messageFlag', full_name='messageProtocol.userPassword.messageFlag', index=2,
      number=3, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='message', full_name='messageProtocol.userPassword.message', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _USERPASSWORD_MESSAGETYPE,
    _USERPASSWORD_MESSAGEVALUE,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=231,
  serialized_end=497,
)


_FRIEND = descriptor.Descriptor(
  name='Friend',
  full_name='messageProtocol.Friend',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='user', full_name='messageProtocol.Friend.user', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='status', full_name='messageProtocol.Friend.status', index=1,
      number=2, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _FRIEND_STATUS,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=499,
  serialized_end=604,
)


_FRIENDLIST = descriptor.Descriptor(
  name='friendlist',
  full_name='messageProtocol.friendlist',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='messageFlag', full_name='messageProtocol.friendlist.messageFlag', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='friend', full_name='messageProtocol.friendlist.friend', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _FRIENDLIST_MESSAGETYPE,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=607,
  serialized_end=753,
)

_COMMUNION.fields_by_name['messageFlag'].enum_type = _COMMUNION_MESSAGETYPE
_COMMUNION_MESSAGETYPE.containing_type = _COMMUNION;
_USERPASSWORD.fields_by_name['messageFlag'].enum_type = _USERPASSWORD_MESSAGETYPE
_USERPASSWORD.fields_by_name['message'].enum_type = _USERPASSWORD_MESSAGEVALUE
_USERPASSWORD_MESSAGETYPE.containing_type = _USERPASSWORD;
_USERPASSWORD_MESSAGEVALUE.containing_type = _USERPASSWORD;
_FRIEND.fields_by_name['status'].enum_type = _FRIEND_STATUS
_FRIEND_STATUS.containing_type = _FRIEND;
_FRIENDLIST.fields_by_name['messageFlag'].enum_type = _FRIENDLIST_MESSAGETYPE
_FRIENDLIST_MESSAGETYPE.containing_type = _FRIENDLIST;
DESCRIPTOR.message_types_by_name['communion'] = _COMMUNION
DESCRIPTOR.message_types_by_name['userPassword'] = _USERPASSWORD
DESCRIPTOR.message_types_by_name['Friend'] = _FRIEND
DESCRIPTOR.message_types_by_name['friendlist'] = _FRIENDLIST

class communion(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _COMMUNION
  
  # @@protoc_insertion_point(class_scope:messageProtocol.communion)

class userPassword(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _USERPASSWORD
  
  # @@protoc_insertion_point(class_scope:messageProtocol.userPassword)

class Friend(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _FRIEND
  
  # @@protoc_insertion_point(class_scope:messageProtocol.Friend)

class friendlist(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _FRIENDLIST
  
  # @@protoc_insertion_point(class_scope:messageProtocol.friendlist)

# @@protoc_insertion_point(module_scope)
